
// This file has been generated by the GUI designer. Do not modify.
namespace KursachAttemp2.View
{
	public partial class FileChoosing
	{
		private global::Gtk.VBox vbox7;

		private global::Gtk.FileChooserWidget filechooserwidget4;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label help_label;

		private global::Gtk.Button choose_file;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget KursachAttemp2.View.FileChoosing
			this.Name = "KursachAttemp2.View.FileChoosing";
			this.Title = global::Mono.Unix.Catalog.GetString("FileChoosing");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child KursachAttemp2.View.FileChoosing.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.filechooserwidget4 = new global::Gtk.FileChooserWidget(((global::Gtk.FileChooserAction)(2)));
			this.filechooserwidget4.Name = "filechooserwidget4";
			this.vbox7.Add(this.filechooserwidget4);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.filechooserwidget4]));
			w1.Position = 0;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.help_label = new global::Gtk.Label();
			this.help_label.Name = "help_label";
			this.help_label.LabelProp = global::Mono.Unix.Catalog.GetString("Please, choose a lable where data is stored");
			this.hbox4.Add(this.help_label);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.help_label]));
			w2.Position = 0;
			w2.Expand = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.choose_file = new global::Gtk.Button();
			this.choose_file.CanFocus = true;
			this.choose_file.Name = "choose_file";
			this.choose_file.UseUnderline = true;
			this.choose_file.Label = global::Mono.Unix.Catalog.GetString("Ok");
			this.hbox4.Add(this.choose_file);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.choose_file]));
			w3.Position = 1;
			this.vbox7.Add(this.hbox4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox4]));
			w4.Position = 1;
			w4.Expand = false;
			this.Add(this.vbox7);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 594;
			this.DefaultHeight = 380;
			this.Show();
			this.choose_file.Clicked += new global::System.EventHandler(this.return_path);
		}
	}
}
